// 서울 지하철 전체 역 데이터 (실시간도착_역정보 기준, 563개 역)
// 자동 생성 파일 - 직접 수정하지 마세요

export const SUBWAY_STATIONS: { stationName: string; lines: string[] }[] = [
  { stationName: "소요산", lines: ["1호선"] },
  { stationName: "동두천", lines: ["1호선"] },
  { stationName: "보산", lines: ["1호선"] },
  { stationName: "동두천중앙", lines: ["1호선"] },
  { stationName: "지행", lines: ["1호선"] },
  { stationName: "덕정", lines: ["1호선"] },
  { stationName: "덕계", lines: ["1호선"] },
  { stationName: "양주", lines: ["1호선"] },
  { stationName: "녹양", lines: ["1호선"] },
  { stationName: "가능", lines: ["1호선"] },
  { stationName: "의정부", lines: ["1호선"] },
  { stationName: "회룡", lines: ["1호선"] },
  { stationName: "망월사", lines: ["1호선"] },
  { stationName: "도봉산", lines: ["1호선", "7호선"] },
  { stationName: "도봉", lines: ["1호선"] },
  { stationName: "방학", lines: ["1호선"] },
  { stationName: "창동", lines: ["1호선", "4호선"] },
  { stationName: "녹천", lines: ["1호선"] },
  { stationName: "월계", lines: ["1호선"] },
  { stationName: "광운대", lines: ["1호선", "경춘선"] },
  { stationName: "석계", lines: ["1호선", "6호선"] },
  { stationName: "신이문", lines: ["1호선"] },
  { stationName: "외대앞", lines: ["1호선"] },
  { stationName: "회기", lines: ["1호선", "경의중앙선", "경춘선"] },
  { stationName: "청량리", lines: ["1호선", "경의중앙선", "경춘선", "수인분당선"] },
  { stationName: "제기동", lines: ["1호선"] },
  { stationName: "신설동", lines: ["1호선", "2호선", "우이신설선"] },
  { stationName: "동묘앞", lines: ["1호선", "6호선"] },
  { stationName: "동대문", lines: ["1호선", "4호선"] },
  { stationName: "종로5가", lines: ["1호선"] },
  { stationName: "종로3가", lines: ["1호선", "3호선", "5호선"] },
  { stationName: "종각", lines: ["1호선"] },
  { stationName: "시청", lines: ["1호선", "2호선"] },
  { stationName: "서울", lines: ["1호선", "4호선", "GTX-A", "경의중앙선", "공항철도"] },
  { stationName: "남영", lines: ["1호선"] },
  { stationName: "용산", lines: ["1호선", "경의중앙선"] },
  { stationName: "노량진", lines: ["1호선", "9호선"] },
  { stationName: "대방", lines: ["1호선", "신림선"] },
  { stationName: "신길", lines: ["1호선", "5호선"] },
  { stationName: "영등포", lines: ["1호선"] },
  { stationName: "신도림", lines: ["1호선", "2호선"] },
  { stationName: "구로", lines: ["1호선"] },
  { stationName: "구일", lines: ["1호선"] },
  { stationName: "개봉", lines: ["1호선"] },
  { stationName: "오류동", lines: ["1호선"] },
  { stationName: "온수", lines: ["1호선", "7호선"] },
  { stationName: "역곡", lines: ["1호선"] },
  { stationName: "소사", lines: ["1호선", "서해선"] },
  { stationName: "부천", lines: ["1호선"] },
  { stationName: "중동", lines: ["1호선"] },
  { stationName: "송내", lines: ["1호선"] },
  { stationName: "부개", lines: ["1호선"] },
  { stationName: "부평", lines: ["1호선"] },
  { stationName: "백운", lines: ["1호선"] },
  { stationName: "동암", lines: ["1호선"] },
  { stationName: "간석", lines: ["1호선"] },
  { stationName: "주안", lines: ["1호선"] },
  { stationName: "도화", lines: ["1호선"] },
  { stationName: "제물포", lines: ["1호선"] },
  { stationName: "도원", lines: ["1호선"] },
  { stationName: "동인천", lines: ["1호선"] },
  { stationName: "인천", lines: ["1호선", "수인분당선"] },
  { stationName: "청산", lines: ["1호선"] },
  { stationName: "전곡", lines: ["1호선"] },
  { stationName: "연천", lines: ["1호선"] },
  { stationName: "광명", lines: ["1호선"] },
  { stationName: "가산디지털단지", lines: ["1호선", "7호선"] },
  { stationName: "독산", lines: ["1호선"] },
  { stationName: "금천구청", lines: ["1호선"] },
  { stationName: "석수", lines: ["1호선"] },
  { stationName: "관악", lines: ["1호선"] },
  { stationName: "안양", lines: ["1호선"] },
  { stationName: "명학", lines: ["1호선"] },
  { stationName: "금정", lines: ["1호선", "4호선"] },
  { stationName: "군포", lines: ["1호선"] },
  { stationName: "당정", lines: ["1호선"] },
  { stationName: "의왕", lines: ["1호선"] },
  { stationName: "성균관대", lines: ["1호선"] },
  { stationName: "화서", lines: ["1호선"] },
  { stationName: "수원", lines: ["1호선", "수인분당선"] },
  { stationName: "세류", lines: ["1호선"] },
  { stationName: "병점", lines: ["1호선"] },
  { stationName: "세마", lines: ["1호선"] },
  { stationName: "오산대", lines: ["1호선"] },
  { stationName: "오산", lines: ["1호선"] },
  { stationName: "진위", lines: ["1호선"] },
  { stationName: "송탄", lines: ["1호선"] },
  { stationName: "서정리", lines: ["1호선"] },
  { stationName: "지제", lines: ["1호선"] },
  { stationName: "평택", lines: ["1호선"] },
  { stationName: "성환", lines: ["1호선"] },
  { stationName: "직산", lines: ["1호선"] },
  { stationName: "두정", lines: ["1호선"] },
  { stationName: "천안", lines: ["1호선"] },
  { stationName: "봉명", lines: ["1호선"] },
  { stationName: "쌍용(나사렛대)", lines: ["1호선"] },
  { stationName: "아산", lines: ["1호선"] },
  { stationName: "탕정", lines: ["1호선"] },
  { stationName: "배방", lines: ["1호선"] },
  { stationName: "온양온천", lines: ["1호선"] },
  { stationName: "신창", lines: ["1호선"] },
  { stationName: "서동탄", lines: ["1호선"] },
  { stationName: "을지로입구", lines: ["2호선"] },
  { stationName: "을지로3가", lines: ["2호선", "3호선"] },
  { stationName: "을지로4가", lines: ["2호선", "5호선"] },
  { stationName: "동대문역사문화공원", lines: ["2호선", "4호선", "5호선"] },
  { stationName: "신당", lines: ["2호선", "6호선"] },
  { stationName: "상왕십리", lines: ["2호선"] },
  { stationName: "왕십리", lines: ["2호선", "5호선", "경의중앙선", "수인분당선"] },
  { stationName: "한양대", lines: ["2호선"] },
  { stationName: "뚝섬", lines: ["2호선"] },
  { stationName: "성수", lines: ["2호선"] },
  { stationName: "건대입구", lines: ["2호선", "7호선"] },
  { stationName: "구의", lines: ["2호선"] },
  { stationName: "강변", lines: ["2호선"] },
  { stationName: "잠실나루", lines: ["2호선"] },
  { stationName: "잠실", lines: ["2호선", "8호선"] },
  { stationName: "잠실새내", lines: ["2호선"] },
  { stationName: "종합운동장", lines: ["2호선", "9호선"] },
  { stationName: "삼성", lines: ["2호선"] },
  { stationName: "선릉", lines: ["2호선", "수인분당선"] },
  { stationName: "역삼", lines: ["2호선"] },
  { stationName: "강남", lines: ["2호선", "신분당선"] },
  { stationName: "교대", lines: ["2호선", "3호선"] },
  { stationName: "서초", lines: ["2호선"] },
  { stationName: "방배", lines: ["2호선"] },
  { stationName: "사당", lines: ["2호선", "4호선"] },
  { stationName: "낙성대", lines: ["2호선"] },
  { stationName: "서울대입구", lines: ["2호선"] },
  { stationName: "봉천", lines: ["2호선"] },
  { stationName: "신림", lines: ["2호선", "신림선"] },
  { stationName: "신대방", lines: ["2호선"] },
  { stationName: "구로디지털단지", lines: ["2호선"] },
  { stationName: "대림", lines: ["2호선", "7호선"] },
  { stationName: "문래", lines: ["2호선"] },
  { stationName: "영등포구청", lines: ["2호선", "5호선"] },
  { stationName: "당산", lines: ["2호선", "9호선"] },
  { stationName: "합정", lines: ["2호선", "6호선"] },
  { stationName: "홍대입구", lines: ["2호선", "경의중앙선", "공항철도"] },
  { stationName: "신촌", lines: ["2호선"] },
  { stationName: "이대", lines: ["2호선"] },
  { stationName: "아현", lines: ["2호선"] },
  { stationName: "충정로", lines: ["2호선", "5호선"] },
  { stationName: "용답", lines: ["2호선"] },
  { stationName: "신답", lines: ["2호선"] },
  { stationName: "용두", lines: ["2호선"] },
  { stationName: "도림천", lines: ["2호선"] },
  { stationName: "양천구청", lines: ["2호선"] },
  { stationName: "신정네거리", lines: ["2호선"] },
  { stationName: "까치산", lines: ["2호선", "5호선"] },
  { stationName: "대화", lines: ["3호선"] },
  { stationName: "주엽", lines: ["3호선"] },
  { stationName: "정발산", lines: ["3호선"] },
  { stationName: "마두", lines: ["3호선"] },
  { stationName: "백석", lines: ["3호선"] },
  { stationName: "대곡", lines: ["3호선", "GTX-A", "경의중앙선", "서해선"] },
  { stationName: "화정", lines: ["3호선"] },
  { stationName: "원당", lines: ["3호선"] },
  { stationName: "원흥", lines: ["3호선"] },
  { stationName: "삼송", lines: ["3호선"] },
  { stationName: "지축", lines: ["3호선"] },
  { stationName: "구파발", lines: ["3호선"] },
  { stationName: "연신내", lines: ["3호선", "6호선", "GTX-A"] },
  { stationName: "불광", lines: ["3호선", "6호선"] },
  { stationName: "녹번", lines: ["3호선"] },
  { stationName: "홍제", lines: ["3호선"] },
  { stationName: "무악재", lines: ["3호선"] },
  { stationName: "독립문", lines: ["3호선"] },
  { stationName: "경복궁", lines: ["3호선"] },
  { stationName: "안국", lines: ["3호선"] },
  { stationName: "충무로", lines: ["3호선", "4호선"] },
  { stationName: "동대입구", lines: ["3호선"] },
  { stationName: "약수", lines: ["3호선", "6호선"] },
  { stationName: "금호", lines: ["3호선"] },
  { stationName: "옥수", lines: ["3호선", "경의중앙선"] },
  { stationName: "압구정", lines: ["3호선"] },
  { stationName: "신사", lines: ["3호선", "신분당선"] },
  { stationName: "잠원", lines: ["3호선"] },
  { stationName: "고속터미널", lines: ["3호선", "7호선", "9호선"] },
  { stationName: "남부터미널", lines: ["3호선"] },
  { stationName: "양재", lines: ["3호선", "신분당선"] },
  { stationName: "매봉", lines: ["3호선"] },
  { stationName: "도곡", lines: ["3호선", "수인분당선"] },
  { stationName: "대치", lines: ["3호선"] },
  { stationName: "학여울", lines: ["3호선"] },
  { stationName: "대청", lines: ["3호선"] },
  { stationName: "일원", lines: ["3호선"] },
  { stationName: "수서", lines: ["3호선", "GTX-A", "수인분당선"] },
  { stationName: "가락시장", lines: ["3호선", "8호선"] },
  { stationName: "경찰병원", lines: ["3호선"] },
  { stationName: "오금", lines: ["3호선", "5호선"] },
  { stationName: "불암산", lines: ["4호선"] },
  { stationName: "상계", lines: ["4호선"] },
  { stationName: "노원", lines: ["4호선", "7호선"] },
  { stationName: "쌍문", lines: ["4호선"] },
  { stationName: "수유", lines: ["4호선"] },
  { stationName: "미아", lines: ["4호선"] },
  { stationName: "미아사거리", lines: ["4호선"] },
  { stationName: "길음", lines: ["4호선"] },
  { stationName: "성신여대입구", lines: ["4호선", "우이신설선"] },
  { stationName: "한성대입구", lines: ["4호선"] },
  { stationName: "혜화", lines: ["4호선"] },
  { stationName: "명동", lines: ["4호선"] },
  { stationName: "회현", lines: ["4호선"] },
  { stationName: "숙대입구", lines: ["4호선"] },
  { stationName: "삼각지", lines: ["4호선", "6호선"] },
  { stationName: "신용산", lines: ["4호선"] },
  { stationName: "이촌", lines: ["4호선", "경의중앙선"] },
  { stationName: "동작", lines: ["4호선", "9호선"] },
  { stationName: "총신대입구(이수)", lines: ["4호선", "7호선"] },
  { stationName: "남태령", lines: ["4호선"] },
  { stationName: "선바위", lines: ["4호선"] },
  { stationName: "경마공원", lines: ["4호선"] },
  { stationName: "대공원", lines: ["4호선"] },
  { stationName: "과천", lines: ["4호선"] },
  { stationName: "정부과천청사", lines: ["4호선"] },
  { stationName: "인덕원", lines: ["4호선"] },
  { stationName: "평촌", lines: ["4호선"] },
  { stationName: "범계", lines: ["4호선"] },
  { stationName: "산본", lines: ["4호선"] },
  { stationName: "수리산", lines: ["4호선"] },
  { stationName: "대야미", lines: ["4호선"] },
  { stationName: "반월", lines: ["4호선"] },
  { stationName: "상록수", lines: ["4호선"] },
  { stationName: "한대앞", lines: ["4호선", "수인분당선"] },
  { stationName: "중앙", lines: ["4호선", "수인분당선"] },
  { stationName: "고잔", lines: ["4호선", "수인분당선"] },
  { stationName: "초지", lines: ["4호선", "수인분당선", "서해선"] },
  { stationName: "안산", lines: ["4호선", "수인분당선"] },
  { stationName: "신길온천", lines: ["4호선", "수인분당선"] },
  { stationName: "정왕", lines: ["4호선", "수인분당선"] },
  { stationName: "오이도", lines: ["4호선", "수인분당선"] },
  { stationName: "방화", lines: ["5호선"] },
  { stationName: "개화산", lines: ["5호선"] },
  { stationName: "김포공항", lines: ["5호선", "9호선", "공항철도", "서해선"] },
  { stationName: "송정", lines: ["5호선"] },
  { stationName: "마곡", lines: ["5호선"] },
  { stationName: "발산", lines: ["5호선"] },
  { stationName: "우장산", lines: ["5호선"] },
  { stationName: "화곡", lines: ["5호선"] },
  { stationName: "신정(은행정)", lines: ["5호선"] },
  { stationName: "목동", lines: ["5호선"] },
  { stationName: "오목교(목동운동장앞)", lines: ["5호선"] },
  { stationName: "양평", lines: ["5호선", "경의중앙선"] },
  { stationName: "영등포시장", lines: ["5호선"] },
  { stationName: "여의도", lines: ["5호선", "9호선"] },
  { stationName: "여의나루", lines: ["5호선"] },
  { stationName: "마포", lines: ["5호선"] },
  { stationName: "공덕", lines: ["5호선", "6호선", "경의중앙선", "공항철도"] },
  { stationName: "애오개", lines: ["5호선"] },
  { stationName: "서대문", lines: ["5호선"] },
  { stationName: "광화문", lines: ["5호선"] },
  { stationName: "청구", lines: ["5호선", "6호선"] },
  { stationName: "신금호", lines: ["5호선"] },
  { stationName: "행당", lines: ["5호선"] },
  { stationName: "마장", lines: ["5호선"] },
  { stationName: "답십리", lines: ["5호선"] },
  { stationName: "장한평", lines: ["5호선"] },
  { stationName: "군자(능동)", lines: ["5호선", "7호선"] },
  { stationName: "아차산(어린이대공원후문)", lines: ["5호선"] },
  { stationName: "광나루(장신대)", lines: ["5호선"] },
  { stationName: "천호(풍납토성)", lines: ["5호선", "8호선"] },
  { stationName: "강동", lines: ["5호선"] },
  { stationName: "길동", lines: ["5호선"] },
  { stationName: "굽은다리(강동구민회관앞)", lines: ["5호선"] },
  { stationName: "명일", lines: ["5호선"] },
  { stationName: "고덕", lines: ["5호선"] },
  { stationName: "상일동", lines: ["5호선"] },
  { stationName: "강일", lines: ["5호선"] },
  { stationName: "미사", lines: ["5호선"] },
  { stationName: "하남풍산", lines: ["5호선"] },
  { stationName: "하남시청", lines: ["5호선"] },
  { stationName: "하남검단산", lines: ["5호선"] },
  { stationName: "둔촌동", lines: ["5호선"] },
  { stationName: "올림픽공원(한국체대)", lines: ["5호선"] },
  { stationName: "방이", lines: ["5호선"] },
  { stationName: "개롱", lines: ["5호선"] },
  { stationName: "거여", lines: ["5호선"] },
  { stationName: "마천", lines: ["5호선"] },
  { stationName: "응암순환(상선)", lines: ["6호선"] },
  { stationName: "역촌", lines: ["6호선"] },
  { stationName: "독바위", lines: ["6호선"] },
  { stationName: "구산", lines: ["6호선"] },
  { stationName: "새절(신사)", lines: ["6호선"] },
  { stationName: "증산(명지대앞)", lines: ["6호선"] },
  { stationName: "디지털미디어시티", lines: ["6호선", "경의중앙선", "공항철도"] },
  { stationName: "월드컵경기장(성산)", lines: ["6호선"] },
  { stationName: "마포구청", lines: ["6호선"] },
  { stationName: "망원", lines: ["6호선"] },
  { stationName: "상수", lines: ["6호선"] },
  { stationName: "광흥창", lines: ["6호선"] },
  { stationName: "대흥(서강대앞)", lines: ["6호선"] },
  { stationName: "효창공원앞", lines: ["6호선", "경의중앙선"] },
  { stationName: "녹사평", lines: ["6호선"] },
  { stationName: "이태원", lines: ["6호선"] },
  { stationName: "한강진", lines: ["6호선"] },
  { stationName: "버티고개", lines: ["6호선"] },
  { stationName: "창신", lines: ["6호선"] },
  { stationName: "보문", lines: ["6호선", "우이신설선"] },
  { stationName: "안암(고대병원앞)", lines: ["6호선"] },
  { stationName: "고려대", lines: ["6호선"] },
  { stationName: "월곡(동덕여대)", lines: ["6호선"] },
  { stationName: "상월곡(한국과학기술연구원)", lines: ["6호선"] },
  { stationName: "돌곶이", lines: ["6호선"] },
  { stationName: "태릉입구", lines: ["6호선", "7호선"] },
  { stationName: "화랑대(서울여대입구)", lines: ["6호선"] },
  { stationName: "봉화산", lines: ["6호선"] },
  { stationName: "신내", lines: ["6호선", "경춘선"] },
  { stationName: "장암", lines: ["7호선"] },
  { stationName: "수락산", lines: ["7호선"] },
  { stationName: "마들", lines: ["7호선"] },
  { stationName: "중계", lines: ["7호선"] },
  { stationName: "하계", lines: ["7호선"] },
  { stationName: "공릉(서울산업대입구)", lines: ["7호선"] },
  { stationName: "먹골", lines: ["7호선"] },
  { stationName: "중화", lines: ["7호선"] },
  { stationName: "상봉", lines: ["7호선", "경의중앙선", "경춘선"] },
  { stationName: "면목", lines: ["7호선"] },
  { stationName: "사가정", lines: ["7호선"] },
  { stationName: "용마산", lines: ["7호선"] },
  { stationName: "중곡", lines: ["7호선"] },
  { stationName: "어린이대공원(세종대)", lines: ["7호선"] },
  { stationName: "뚝섬유원지", lines: ["7호선"] },
  { stationName: "청담", lines: ["7호선"] },
  { stationName: "강남구청", lines: ["7호선", "수인분당선"] },
  { stationName: "학동", lines: ["7호선"] },
  { stationName: "논현", lines: ["7호선", "신분당선"] },
  { stationName: "반포", lines: ["7호선"] },
  { stationName: "내방", lines: ["7호선"] },
  { stationName: "남성", lines: ["7호선"] },
  { stationName: "숭실대입구(살피재)", lines: ["7호선"] },
  { stationName: "상도(중앙대앞)", lines: ["7호선"] },
  { stationName: "장승배기", lines: ["7호선"] },
  { stationName: "신대방삼거리", lines: ["7호선"] },
  { stationName: "보라매", lines: ["7호선", "신림선"] },
  { stationName: "신풍", lines: ["7호선"] },
  { stationName: "남구로", lines: ["7호선"] },
  { stationName: "철산", lines: ["7호선"] },
  { stationName: "광명사거리", lines: ["7호선"] },
  { stationName: "천왕", lines: ["7호선"] },
  { stationName: "까치울", lines: ["7호선"] },
  { stationName: "부천종합운동장", lines: ["7호선", "서해선"] },
  { stationName: "춘의", lines: ["7호선"] },
  { stationName: "신중동", lines: ["7호선"] },
  { stationName: "부천시청", lines: ["7호선"] },
  { stationName: "상동", lines: ["7호선"] },
  { stationName: "삼산체육관", lines: ["7호선"] },
  { stationName: "굴포천", lines: ["7호선"] },
  { stationName: "부평구청", lines: ["7호선"] },
  { stationName: "산곡", lines: ["7호선"] },
  { stationName: "석남", lines: ["7호선"] },
  { stationName: "별내", lines: ["8호선", "경춘선"] },
  { stationName: "다산", lines: ["8호선"] },
  { stationName: "동구릉", lines: ["8호선"] },
  { stationName: "구리", lines: ["8호선", "경의중앙선"] },
  { stationName: "장자호수공원", lines: ["8호선"] },
  { stationName: "암사역사공원", lines: ["8호선"] },
  { stationName: "암사", lines: ["8호선"] },
  { stationName: "강동구청", lines: ["8호선"] },
  { stationName: "몽촌토성(평화의문)", lines: ["8호선"] },
  { stationName: "석촌", lines: ["8호선", "9호선"] },
  { stationName: "송파", lines: ["8호선"] },
  { stationName: "문정", lines: ["8호선"] },
  { stationName: "장지", lines: ["8호선"] },
  { stationName: "복정", lines: ["8호선", "수인분당선"] },
  { stationName: "남위례", lines: ["8호선"] },
  { stationName: "산성", lines: ["8호선"] },
  { stationName: "남한산성입구(성남법원,검찰청)", lines: ["8호선"] },
  { stationName: "단대오거리", lines: ["8호선"] },
  { stationName: "신흥", lines: ["8호선"] },
  { stationName: "수진", lines: ["8호선"] },
  { stationName: "모란", lines: ["8호선", "수인분당선"] },
  { stationName: "개화", lines: ["9호선"] },
  { stationName: "공항시장", lines: ["9호선"] },
  { stationName: "신방화", lines: ["9호선"] },
  { stationName: "마곡나루", lines: ["9호선", "공항철도"] },
  { stationName: "양천향교", lines: ["9호선"] },
  { stationName: "가양", lines: ["9호선"] },
  { stationName: "증미", lines: ["9호선"] },
  { stationName: "등촌", lines: ["9호선"] },
  { stationName: "염창", lines: ["9호선"] },
  { stationName: "신목동", lines: ["9호선"] },
  { stationName: "선유도", lines: ["9호선"] },
  { stationName: "국회의사당", lines: ["9호선"] },
  { stationName: "샛강", lines: ["9호선", "신림선"] },
  { stationName: "노들", lines: ["9호선"] },
  { stationName: "흑석", lines: ["9호선"] },
  { stationName: "구반포", lines: ["9호선"] },
  { stationName: "신반포", lines: ["9호선"] },
  { stationName: "사평", lines: ["9호선"] },
  { stationName: "신논현", lines: ["9호선", "신분당선"] },
  { stationName: "언주", lines: ["9호선"] },
  { stationName: "선정릉", lines: ["9호선", "수인분당선"] },
  { stationName: "삼성중앙", lines: ["9호선"] },
  { stationName: "봉은사", lines: ["9호선"] },
  { stationName: "삼전", lines: ["9호선"] },
  { stationName: "석촌고분", lines: ["9호선"] },
  { stationName: "송파나루", lines: ["9호선"] },
  { stationName: "한성백제", lines: ["9호선"] },
  { stationName: "올림픽공원", lines: ["9호선"] },
  { stationName: "둔촌오륜", lines: ["9호선"] },
  { stationName: "중앙보훈병원", lines: ["9호선"] },
  { stationName: "운정중앙", lines: ["GTX-A"] },
  { stationName: "킨텍스", lines: ["GTX-A"] },
  { stationName: "성남", lines: ["GTX-A", "경강선"] },
  { stationName: "구성", lines: ["GTX-A", "수인분당선"] },
  { stationName: "동탄", lines: ["GTX-A"] },
  { stationName: "서빙고", lines: ["경의중앙선"] },
  { stationName: "한남", lines: ["경의중앙선"] },
  { stationName: "응봉", lines: ["경의중앙선"] },
  { stationName: "중랑", lines: ["경의중앙선", "경춘선"] },
  { stationName: "망우", lines: ["경의중앙선", "경춘선"] },
  { stationName: "양원", lines: ["경의중앙선"] },
  { stationName: "도농", lines: ["경의중앙선"] },
  { stationName: "양정", lines: ["경의중앙선"] },
  { stationName: "덕소", lines: ["경의중앙선"] },
  { stationName: "도심", lines: ["경의중앙선"] },
  { stationName: "팔당", lines: ["경의중앙선"] },
  { stationName: "운길산", lines: ["경의중앙선"] },
  { stationName: "양수", lines: ["경의중앙선"] },
  { stationName: "신원", lines: ["경의중앙선"] },
  { stationName: "국수", lines: ["경의중앙선"] },
  { stationName: "아신", lines: ["경의중앙선"] },
  { stationName: "오빈", lines: ["경의중앙선"] },
  { stationName: "원덕", lines: ["경의중앙선"] },
  { stationName: "용문", lines: ["경의중앙선"] },
  { stationName: "지평", lines: ["경의중앙선"] },
  { stationName: "서강대", lines: ["경의중앙선"] },
  { stationName: "가좌", lines: ["경의중앙선"] },
  { stationName: "수색", lines: ["경의중앙선"] },
  { stationName: "한국항공대", lines: ["경의중앙선"] },
  { stationName: "강매", lines: ["경의중앙선"] },
  { stationName: "행신", lines: ["경의중앙선"] },
  { stationName: "능곡", lines: ["경의중앙선", "서해선"] },
  { stationName: "곡산", lines: ["경의중앙선", "서해선"] },
  { stationName: "백마", lines: ["경의중앙선", "서해선"] },
  { stationName: "풍산", lines: ["경의중앙선", "서해선"] },
  { stationName: "일산", lines: ["경의중앙선", "서해선"] },
  { stationName: "탄현", lines: ["경의중앙선"] },
  { stationName: "야당", lines: ["경의중앙선"] },
  { stationName: "운정", lines: ["경의중앙선"] },
  { stationName: "금릉", lines: ["경의중앙선"] },
  { stationName: "금촌", lines: ["경의중앙선"] },
  { stationName: "월롱", lines: ["경의중앙선"] },
  { stationName: "파주", lines: ["경의중앙선"] },
  { stationName: "문산", lines: ["경의중앙선"] },
  { stationName: "운천", lines: ["경의중앙선"] },
  { stationName: "임진강", lines: ["경의중앙선"] },
  { stationName: "신촌(경의중앙선)", lines: ["경의중앙선"] },
  { stationName: "계양", lines: ["공항철도"] },
  { stationName: "검암", lines: ["공항철도"] },
  { stationName: "운서", lines: ["공항철도"] },
  { stationName: "공항화물청사", lines: ["공항철도"] },
  { stationName: "인천공항1터미널", lines: ["공항철도"] },
  { stationName: "인천공항2터미널", lines: ["공항철도"] },
  { stationName: "청라국제도시", lines: ["공항철도"] },
  { stationName: "영종", lines: ["공항철도"] },
  { stationName: "갈매", lines: ["경춘선"] },
  { stationName: "퇴계원", lines: ["경춘선"] },
  { stationName: "사릉", lines: ["경춘선"] },
  { stationName: "금곡", lines: ["경춘선"] },
  { stationName: "평내호평", lines: ["경춘선"] },
  { stationName: "천마산", lines: ["경춘선"] },
  { stationName: "마석", lines: ["경춘선"] },
  { stationName: "대성리", lines: ["경춘선"] },
  { stationName: "청평", lines: ["경춘선"] },
  { stationName: "상천", lines: ["경춘선"] },
  { stationName: "가평", lines: ["경춘선"] },
  { stationName: "굴봉산", lines: ["경춘선"] },
  { stationName: "백양리", lines: ["경춘선"] },
  { stationName: "강촌", lines: ["경춘선"] },
  { stationName: "김유정", lines: ["경춘선"] },
  { stationName: "남춘천", lines: ["경춘선"] },
  { stationName: "춘천", lines: ["경춘선"] },
  { stationName: "서울숲", lines: ["수인분당선"] },
  { stationName: "압구정로데오", lines: ["수인분당선"] },
  { stationName: "한티", lines: ["수인분당선"] },
  { stationName: "구룡", lines: ["수인분당선"] },
  { stationName: "개포동", lines: ["수인분당선"] },
  { stationName: "대모산입구", lines: ["수인분당선"] },
  { stationName: "가천대", lines: ["수인분당선"] },
  { stationName: "태평", lines: ["수인분당선"] },
  { stationName: "야탑", lines: ["수인분당선"] },
  { stationName: "이매", lines: ["수인분당선", "경강선"] },
  { stationName: "서현", lines: ["수인분당선"] },
  { stationName: "수내", lines: ["수인분당선"] },
  { stationName: "정자", lines: ["수인분당선", "신분당선"] },
  { stationName: "미금", lines: ["수인분당선", "신분당선"] },
  { stationName: "오리", lines: ["수인분당선"] },
  { stationName: "죽전", lines: ["수인분당선"] },
  { stationName: "보정", lines: ["수인분당선"] },
  { stationName: "신갈", lines: ["수인분당선"] },
  { stationName: "기흥", lines: ["수인분당선"] },
  { stationName: "상갈", lines: ["수인분당선"] },
  { stationName: "청명", lines: ["수인분당선"] },
  { stationName: "영통", lines: ["수인분당선"] },
  { stationName: "망포", lines: ["수인분당선"] },
  { stationName: "매탄권선", lines: ["수인분당선"] },
  { stationName: "수원시청", lines: ["수인분당선"] },
  { stationName: "매교", lines: ["수인분당선"] },
  { stationName: "고색", lines: ["수인분당선"] },
  { stationName: "오목천", lines: ["수인분당선"] },
  { stationName: "어천", lines: ["수인분당선"] },
  { stationName: "야목", lines: ["수인분당선"] },
  { stationName: "사리", lines: ["수인분당선"] },
  { stationName: "달월", lines: ["수인분당선"] },
  { stationName: "월곶", lines: ["수인분당선"] },
  { stationName: "소래포구", lines: ["수인분당선"] },
  { stationName: "인천논현", lines: ["수인분당선"] },
  { stationName: "호구포", lines: ["수인분당선"] },
  { stationName: "남동인더스파크", lines: ["수인분당선"] },
  { stationName: "원인재", lines: ["수인분당선"] },
  { stationName: "연수", lines: ["수인분당선"] },
  { stationName: "송도", lines: ["수인분당선"] },
  { stationName: "인하대", lines: ["수인분당선"] },
  { stationName: "숭의", lines: ["수인분당선"] },
  { stationName: "신포", lines: ["수인분당선"] },
  { stationName: "양재시민의숲", lines: ["신분당선"] },
  { stationName: "청계산입구", lines: ["신분당선"] },
  { stationName: "판교", lines: ["신분당선", "경강선"] },
  { stationName: "동천", lines: ["신분당선"] },
  { stationName: "수지구청", lines: ["신분당선"] },
  { stationName: "성복", lines: ["신분당선"] },
  { stationName: "상현", lines: ["신분당선"] },
  { stationName: "광교중앙", lines: ["신분당선"] },
  { stationName: "광교", lines: ["신분당선"] },
  { stationName: "삼동", lines: ["경강선"] },
  { stationName: "경기광주", lines: ["경강선"] },
  { stationName: "초월", lines: ["경강선"] },
  { stationName: "곤지암", lines: ["경강선"] },
  { stationName: "신둔도예촌", lines: ["경강선"] },
  { stationName: "이천", lines: ["경강선"] },
  { stationName: "부발", lines: ["경강선"] },
  { stationName: "세종왕릉", lines: ["경강선"] },
  { stationName: "여주", lines: ["경강선"] },
  { stationName: "북한산우이", lines: ["우이신설선"] },
  { stationName: "솔밭공원", lines: ["우이신설선"] },
  { stationName: "4.19 민주묘지", lines: ["우이신설선"] },
  { stationName: "가오리", lines: ["우이신설선"] },
  { stationName: "화계", lines: ["우이신설선"] },
  { stationName: "삼양", lines: ["우이신설선"] },
  { stationName: "삼양사거리", lines: ["우이신설선"] },
  { stationName: "솔샘", lines: ["우이신설선"] },
  { stationName: "북한산보국문", lines: ["우이신설선"] },
  { stationName: "정릉", lines: ["우이신설선"] },
  { stationName: "원종", lines: ["서해선"] },
  { stationName: "소새울", lines: ["서해선"] },
  { stationName: "시흥대야", lines: ["서해선"] },
  { stationName: "신천", lines: ["서해선"] },
  { stationName: "신현", lines: ["서해선"] },
  { stationName: "시흥시청", lines: ["서해선"] },
  { stationName: "시흥능곡", lines: ["서해선"] },
  { stationName: "달미", lines: ["서해선"] },
  { stationName: "선부", lines: ["서해선"] },
  { stationName: "시우", lines: ["서해선"] },
  { stationName: "원시", lines: ["서해선"] },
  { stationName: "서울지방병무청", lines: ["신림선"] },
  { stationName: "보라매공원", lines: ["신림선"] },
  { stationName: "보라매병원", lines: ["신림선"] },
  { stationName: "당곡", lines: ["신림선"] },
  { stationName: "서원", lines: ["신림선"] },
  { stationName: "서울대벤처타운", lines: ["신림선"] },
  { stationName: "관악산", lines: ["신림선"] },
]